### ISSUE TITLE
SAFE API Playground Crash

### ISSUE THREAD

**Issue by josephm1** [maidsafe/safe_examples#275] opened 2017-09-17 18:14 UTC
The SAFE API Playground crashes any time you try to choose a file in the NFS Create section. I suspect this might have something to with
```javascript
 let fileReader = new FileReader();

      fileReader.onload = function(event) {
       let fileBuffer = new Buffer(event.target.result);
       window.fileContent = fileBuffer;
        }

        fileReader.readAsArrayBuffer(event.target.files[0]);
      });   
``` 
in the safe_examples/safe_web_api_playground/static/js/init_snippets.js line 62-67 as the Buffer function is not implemented in  the current SAFE Browser.

**Comment by hunterlester** [comment] 2017-09-18 15:30
@josephm1 Thank you for catching that mistake.

The browser crashing is another issues. If you comment out the part that is using `new Buffer` you'll see that it still crashes.

I started documenting it here:
https://maidsafe.atlassian.net/browse/MAID-2257

**Comment by DaBrown95** [comment] 2017-10-23 13:33
I am running into this issue too, macOS 10.13. Can easily reproduce. So it looks like this issue is not unique to a Windows build.

**Comment by DaBrown95** [comment] 2017-10-23 15:06
Just tested under Ubuntu 17.10 and the issue still occurs.

**Comment by josephm1** [comment] 2017-11-19 14:15
Any updates on uploading files with the browser?

**Comment by hunterlester** [comment] 2017-11-20 13:58
Beaker and Rotunda community may have been experiencing the same issue. We're sprinting on milestones for the next few weeks but I'd like to test the latest versions of Beaker browser to see if it has been fixed: https://twitter.com/BeakerBrowser/status/930843653400137728

**Comment by hunterlester** [comment] 2017-12-18 17:56
At the moment we won't be resolving this issue in SAFE Browser since we'll soon be using the new browser. https://github.com/joshuef/peruse, where it has been completely resolved.

**Closed by hunterlester** 2017-12-18 17:56 UTC
